### ISSUE TITLE
Evidence Rating and Evidence Summary should be required fields in Add Evidence form

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-client#670]

**Comment by malachig** [comment]
I believe this should be Evidence Rating and Evidence Summary.  I think Evidence Level is already required.

**Comment by jmcmichael** [comment]
Done. I've also made Evidence Type required, as Clinical Significance is already a required field and Evidence Type must be selected before selecting a Clinical Significance.

**Comment by acoffman** [comment]
https://civicdb.org/events/genes/14/summary/variants/554/summary/evidence/7986/summary#evidence

**Comment by cgrisdale** [comment]
I noticed when submitting an EID that if you select a star rating and then click on it a second time it removes the rating but you still have the ability to submit.

**Comment by jmcmichael** [comment]
@cgrisdale - yes, thank you, that appears to be the problem. Should be pretty straightforward for me to require a least a rating of 1 and add a custom error message for the field.
